- uses: contentful/actions-app-deploy@v1
  with:
    organization-id: ${{ secrets.ORGANIZATION_ID }}
    app-definition-id: ${{ secrets.APP_DEFINITION_ID }}
    access-token: ${{ secrets.ACCESS_TOKEN }}
    folder: build   